name: GitHub CI

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Compile Java
              run: ./gradlew :app:compileJava


    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run JUnit Tests
              run: ./gradlew :app:test

   
    formatting:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Check Spotless Formatting
              run: ./gradlew :app:spotlessCheck
